[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ wealth-icos-api ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running testRunner.Runner
Scenario Outline: Verify the Post Contact Notes API with invalid PersonId # src/test/resources/Features/CreateContactNotes-WrongPersonId.feature:18
Before All
May 12, 2025 6:37:40 AM hooks.CucumberHooks beforeScenario
INFO: Before Scenario: Test is starting!
May 12, 2025 6:37:45 AM utilities.CucumberLogger PrintStatus
INFO: Value is: Access Token is51kgS0HaC3LUkgKIqhQfKYvEdfvZ
May 12, 2025 6:37:45 AM utilities.CucumberLogger PrintStatus
INFO: Value is: Access Token  is{accessToken=51kgS0HaC3LUkgKIqhQfKYvEdfvZ, tokenType=Bearer}
  Given Send Request to get Authentication Token for ICOS                 # stepDefinations.GetUserSteps.sendRequestToGetAuthenticationTokenForICOS()
May 12, 2025 6:37:46 AM utilities.CucumberLogger PrintStatus
INFO: Value is: Tyk Token iseyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzdXAtYW1pd3Mtand0LWdlbmVyYXRvciIsInN1YiI6IlJCU0MkQ0xNX09OQk9BUkRJTkciLCJhdWQiOiJBTUlXZWJTZXJ2aWNlcyIsImV4cCI6MTc0NzAyOTE2NiwiaWF0IjoxNzQ3MDI4MjY2LCJhdmFsb3FfYnVfaWQiOiI2In0.ctCwUl1sityrHNsZX_fqe_1hvs03HND2s9B6hEzG6YN8q_iukxbW1Iyvos3M5fpCEdI9LpDZLP5Y2zwqsV-kSgh7oeT5Wt0Z0brGnfLN-MNsOvPOS3a-n7ANVglXYhqKFJ3L4h0JxBnxyNq9-BVD_Ua1OuR1FahYSlzqCo0m8WW_yvMm553eR2o-WLW7ttMcjggD8fIHg7J9j28TBNJQaWaT0lCK95A8BcmmQ-OJxKLcsRd4bMp8V5wxiMGhfRyJKh7DKFH3p8b1xGiCV19QnT_G5D4oEo-5uIjXO3wl-niYCNSAngNjzmjI_qPT-Zq73EvSq7Hw0NxYfeR23gf-8Q
  When I generate the JWT Token                                           # stepDefinations.GetUserSteps.iGenerateTheJWTToken()
May 12, 2025 6:37:47 AM utilities.CucumberLogger PrintStatus
INFO: Value is: Response is{"description":"Validation Errors","validationErrors":[{"value":"ghgf","error":"Person not found"}]}
  Then Send POST ContactNote Request with below details                   # stepDefinations.ContactNotesSteps.sendPOSTContactNoteRequestWithDetails(io.cucumber.datatable.DataTable)
    | personIds   | ghgf        |
    | subject     | Testsubject |
    | notes       | Testnote    |
    | hasFollowup | false       |
  And I verify the Status Code for Contact Notes "400"                    # stepDefinations.ContactNotesSteps.iVerifyTheStatusCodeForContactNotes(java.lang.String)
  And I verify the validation error response with below details           # stepDefinations.ContactNotesSteps.iVerifyTheValidationErrorResponse(java.lang.String,java.lang.String)
    | description   | Validation Errors |
    | error message | Person not found  |
      io.cucumber.core.exception.CucumberException: Step [I verify the validation error response with below details] is defined with 2 parameters at 'stepDefinations.ContactNotesSteps.iVerifyTheValidationErrorResponse(java.lang.String,java.lang.String)'.
However, the gherkin step has 1 arguments:
 * Table:
      | description   | Validation Errors |
      | error message | Person not found  |
Step text: I verify the validation error response with below details
	at io.cucumber.core.runner.PickleStepDefinitionMatch.arityMismatch(PickleStepDefinitionMatch.java:82)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:41)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:81)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:53)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.lambda$run$0(PickleRunners.java:151)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:136)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:136)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:148)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:144)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:28)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at io.cucumber.junit.FeatureRunner.run(FeatureRunner.java:137)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:199)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:89)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runFeatures$6(CucumberExecutionContext.java:147)
	at io.cucumber.core.runtime.CucumberExecutionContext.execute(CucumberExecutionContext.java:162)
	at io.cucumber.core.runtime.CucumberExecutionContext.runFeatures(CucumberExecutionContext.java:145)
	at io.cucumber.junit.Cucumber$StartAndFinishTestRun.evaluate(Cucumber.java:229)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:63)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
May 12, 2025 6:37:50 AM tech.grasshopper.pdf.PDFCucumberReport collectReportConfiguration
INFO: PDF report configuration YAML file not found. Using default settings.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.66 s <<< FAILURE! - in testRunner.Runner
[ERROR] Create Contact Notes API with invalid PersonId.Verify the Post Contact Notes API with invalid PersonId  Time elapsed: 8.496 s  <<< ERROR!
io.cucumber.core.exception.CucumberException: 
Step [I verify the validation error response with below details] is defined with 2 parameters at 'stepDefinations.ContactNotesSteps.iVerifyTheValidationErrorResponse(java.lang.String,java.lang.String)'.
However, the gherkin step has 1 arguments:
 * Table:
      | description   | Validation Errors |
      | error message | Person not found  |
Step text: I verify the validation error response with below details
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   Step [I verify the validation error response with below details] is defined with 2 parameters at 'stepDefinations.ContactNotesSteps.iVerifyTheValidationErrorResponse(java.lang.String,java.lang.String)'.
However, the gherkin step has 1 arguments:
 * Table:
      | description   | Validation Errors |
      | error message | Person not found  |
Step text: I verify the validation error response with below details
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 


Feature: Create Contact Notes API with invalid PersonId

  Scenario Outline: Verify the Post Contact Notes API with invalid PersonId
    Given Send Request to get Authentication Token for ICOS
    When I generate the JWT Token
    Then Send POST ContactNote Request with below details
      | personIds    | <personIds>   |
      | subject      | <subject>     |
      | notes        | <notes>       |
      | hasFollowup  | <hasFollowup> |
    And I verify the Status Code for Contact Notes "<statusCode>"
    And I verify the validation error response with below details
      | description   | <description> |
      | error message | <error>       |

    Examples:
      | personIds | subject      | notes     | hasFollowup | statusCode | description       | error             |
      | ghgf      | Testsubject  | Testnote  | false       | 400        | Validation Errors | Person not found  |

    @And("I verify the validation error response with below details")
    public void iVerifyTheValidationErrorResponse(String strExpDescription, String strExpErrorMessage) throws Exception {
        String strActualDescription = JsonHelper.extractStringField(response, "description");
        ExtentCucumberAdapter.addTestStepLog("Actual description: " + strActualDescription);
        Assert.assertEquals(strActualDescription, strExpDescription, "Mismatch in description");

        // Extracting the first validation error message
        String strActualErrorMessage = JsonHelper.extractStringFieldFromArray(response, "validationErrors", 0, "error");
        ExtentCucumberAdapter.addTestStepLog("Actual error message: " + strActualErrorMessage);
        Assert.assertEquals(strActualErrorMessage, strExpErrorMessage, "Mismatch in error message");
    }

JsonHelper method -     public static String extractStringFieldFromArray(Response response, String arrayField, int index, String fieldName) {
        return response.jsonPath().getString(arrayField + "[" + index + "]." + fieldName);
    }
